export const environment = {
  production: true,
  id: 0,
  nome: '',
  sobrenome: '',
  email: '',
  foto: '',
  razaoSocial: '',
  numero: '',
  linkedin: '',
  github: '',
  descricaoPerfil: '',
  dataNascimento: {},
  token: '',
};
